import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ReactQueryWrapper } from "../components/wrappers/reactQuery";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-br from-[#0b0c10] via-[#1a1a2e] to-[#0b0c10] text-white min-h-screen flex items-center justify-center">
        <div className="w-full bg-[#161a23]/70 backdrop-blur-md rounded-2xl shadow-2xl border border-gray-800">
          <ReactQueryWrapper>{children}</ReactQueryWrapper>
        </div>
      </body>
    </html>
  );
}
